- testador/zzdolar.sh
- zz/zzdolar.sh
Tentei corrigir o bug #155  que eu mesmo abri. Utilizei outra página, já que a página anterior não apresentava cotações nenhuma.
Espero que tenha ficado legal! :-)
> Correção do zzdolar

- zz/zzhastebin.sh
Função que gera link para arquivos de texto.
> Função nova: zzhastebin - Gera link para arquivos de texto em geral

- zz/zzfutebol.sh
Olá pessoal,
fiz as adaptações. Qualquer sugestão ou correção são sempre muito bem vindas!
> ZZFutebol - Adaptação.

- off/zzglobo.sh
Encontrei o site http://vejonatv.com.br/programacao/globo-rede.html que traz a programação da Rede Globo.
> REATIVADA: zzglobo

- zz/zziostat.sh
Monitora a utilização dos discos para Linux usando o comando iostat
> zziostat.sh

- .travis.yml
Agora voltou a funcionar.
Fixes #248
> Adiciona zzbraille ao Travis

- testador/zzconjugar.sh
- zz/zzconjugar.sh
- zz/zzdicportugues.sh
Usando apenas ``` zztool source ``` e muitas outras ``` zz's ``` como suporte.
Uma prova de conceito.
> Função nova: zzconjugar - Conjugação de verbos.

- info/autores.sh
- release/2iso.sh
- util/alinhamento.sh
- util/nanny.sh
- Revendo alguns filtros
- Reordenado código
- Modificando exceções, sendo mais específica em ``` alinhamento.sh ``` e mais genérica em ``` nanny.sh ```.
> Info, release e util: Revisão.

- testador/zzconjugar.sh
- zz/zzconjugar.sh
As definições em alguns casos ganharam um texto explicativo mais detalhado que vale a pena ser exibido.
Para um ganho informativo, é aceitável uma perda estética.
> zzconjugar: Alterando definição, menos estético e mais informativo.

- .travis.yml
- testador/zzcinemais.sh
- testador/zzcinemark.sh
- testador/zzcinepolis.sh
- testador/zzcineuci.sh
- zz/zzcinemais.sh
- zz/zzcinemark.sh
- zz/zzcinepolis.sh
- zz/zzcineuci.sh
Mais um PR para atender a issue #47 e issue #121
> Novos testes e correções para funções de cinema.

- .travis.yml
Medida temporária, pra contornar os problemas descritos em https://github.com/funcoeszz/funcoeszz/issues/355
> CI: Exclui testes da zzlinux no Linux

- .travis.yml
> Desativa Travis rodando no OS X

- zz/zzfrenteverso2pdf.sh
Para ficar igual as demais funções:
```
$ grep -C 1 'Nota:.*requer' zz/*
zz/zzcinclude.sh-# Licença: GPL
zz/zzcinclude.sh:# Nota: requer cpp
zz/zzcinclude.sh-# ----------------------------------------------------------------------------
--
--
zz/zzfrenteverso2pdf.sh-# Combina 2 arquivos, frentes.pdf e versos.pdf, em um único frenteverso.pdf.
zz/zzfrenteverso2pdf.sh:# Nota: requer o programa "pdftk"!
zz/zzfrenteverso2pdf.sh-# Opções:
--
--
zz/zziostat.sh-# Licença: GPL
zz/zziostat.sh:# Nota: requer iostat
zz/zziostat.sh-# ----------------------------------------------------------------------------
--
--
zz/zzloteria.sh-# Requisitos: zzlimpalixo
zz/zzloteria.sh:# Nota: requer links
zz/zzloteria.sh-# ----------------------------------------------------------------------------
--
-- …
```
> zzfrenteverso2pdf: Arruma o padrão de Nota: no cabeçalho

- testador/zzcinepolis.sh
- zz/zzcinepolis.sh
> zzcinepolis: Nova listagem, ajuste de filtros e nova adaptação no testador.

- off/zzkill.sh
- off/zzrandbackground.sh
- off/zzrelansi.sh
Esqueci de incluir a linha mágica. Tou enferrujado 😄 
```console
$ ./util/nanny.sh
...
* Funções desativadas sem data e motivo para o desligamento
off/zzkill.sh
off/zzrandbackground.sh
off/zzrelansi.sh
```
> Nanny: Funções desativadas sem data e motivo para o desligamento

- testador/zzcinemais.sh
- zz/zzcinemais.sh
> zzcinemais: testes melhorados, trata código inválido

- testador/zzcinemark.sh
- zz/zzcinemark.sh
> zzcinemark: testes melhorados, trata código inválido

- testador/zzcineuci.sh
- zz/zzcineuci.sh
- Removidos \r indesejados do cache
- Removido cabeçalho desnecessário nalista de cidades
- Tratando códigos inválidos
- Apesar do --help dizer que ela pode receber um nome de cidade, não havia
código pra lidar com isso
Veja #397
> zzcineuci: testes melhorados, trata código inválido

- funcoeszz
- testador/zzzz.sh
> Respeita $ZZBROWSER definida pelo usuário (+testes)

- zz/zznoticiaslinux.sh
Veja discussão em #395 
Nos meus testes aqui funciona OK sem.
@itamarnet: confirma aí?
> zznoticiaslinux: não precisa mais do zzfeed --iso

- zz/zzcinemais.sh
> zzcinemais: Remove opção obsoleta -o para zztool source

- Dockerfile
> Docker: Instala o unzip, necessário para a zzloteria

- zz/zznerdcast.sh
A primeira linha do cabeçalho é importante e deve ser um resumo sucinto do que faz a função.
> zznerdcast: Arruma descrição no padrão das ZZ

- zz/zzrastreamento.sh
Abro este PR a fim de obter revisões e dicas de como melhorá-lo.
> WIP - zzrastreamento: Compatibiliza com SRO atual

- testador/zzfilme.sh
- zz/zzfilme.sh
A função faz uma pesquisa através da API do site https://www.omdbapi.com/ e retorna algumas informações em relação ao filme encontrado.
Tem a opção -t para realizar a tradução da sinopse para português, utilizando o Google Translate.
> Função nova: zzfilme - Pesquisa informações sobre filmes.

- zz/macadress.sh
- zz/zzmacaddress.sh
Nova Função que Lista todos os MAC address disponíveis.
> add zzmacaddress.sh 

- testador/zzcnpj.sh
- testador/zzcpf.sh
- zz/zzcnpj.sh
- zz/zzcpf.sh
Correção de validação de cpf e cnpj começando com zero.
Inclusão de testes de cpf e cnpj começando com zero.
> Correção de validação de cpf e cnpj começando com zero.

- zz/zzcinemais.sh
- zz/zzcineuci.sh
- zz/zzcnpj.sh
- zz/zzunicode.sh
Estas funções acessam a internet, mas estavam sem a tag 'internet'.
> Adiciona tag 'internet' nas funções que faltavam

- testador/zzdicportugues.sh
- testador/zzdolar.sh
- testador/zzexcuse.sh
- testador/zzjquery.sh
- testador/zzpais.sh
- testador/zzpgsql.sh
- testador/zzphp.sh
- testador/zzsigla.sh
- testador/zztempo.sh
- testador/zzunicode.sh
Arrumei alguns testes que estavam quebrados por detalhes pequenos, que não precisam de ajustes nas suas respectivas funções ZZ.
> Ajustes simples nos testes

- funcoeszz
Para que estas funções fiquem no mesmo padrão das demais funções.
Essas funções já tiveram muitas versões, mas como é difícil agora
saber exatamente qual seria o número de versão certo, deixei como 1
mesmo.
> Funções-base: Cabeçalho: Adiciona campos Versão e Requisitos

- funcoeszz
- Remove código duplicado
- Arruma bug no desligamento de funções na versão tudo-em-um
> Melhorias no tratamento da ZZOFF

- testador/zzcnpj.sh
- testador/zzcoin.sh
- testador/zzpais.sh
Os resultados apresentados são válidos, apenas havendo mudança nas resposta recebida do site.
> Combo zzcnpj, zzcoin e zzpais: Adequando resultados dos testes, que não são erros.

- testador/zztool.sh
- zz/zztool.sh
Otimização dos parâmetros para tr em função list2lines, multi_stdin e adição de testes unitários para esta função.
Achei oportuno criar um pull request para isto :)
Se achar algum problema por favor avise. 
Valeu pela ferramenta!
> Melhorias na função list2lines

- funcoeszz
> Comentários sobre a resolução do parâmetro $0 em bash.

- testador/zzcineuci.sh
- testador/zzcnpj.sh
- testador/zzdicesperanto.sh
- testador/zzf1.sh
- testador/zznerdcast.sh
- zz/zzcnpj.sh
- zz/zzdicesperanto.sh
- zz/zznumero.sh
- zz/zzsecurity.sh
Um pacote com ajustes simples nas funções e em seus testes.
Veja os commits individuais para mais informações.
> Arruma testes: cineuci, cnpj, numero, dicesperanto, f1, nerdcast, security
