testador/zzsigla.sh, zz/zzsigla.sh
A API do site para realizar buscas mudou. A URL agora está muito mais simple.
Tratamento do resultado para remover espaços iniciais e deixar apenas 3 espaços entre a sigla e o significado.
Signed-off-by: Paulo Vital <pvital@gmail.com>
=> zzsigla: Correção da URL - V2

testador/zzcpf.sh, zz/zzcpf.sh
No próprio site da receita podemos obter esse erro, diferente de 111.111.111-11 que é um CPF válido.
=> CPF não pode conter apenas zeros

testador/zzselic.sh, zz/zzselic.sh
Função para obter a taxa SELIC entre os dias úteis de um dado intervalo.
```
$ zzselic 01/06/2015 10/06/2015
Data        Taxa (%a.a.)
01/06/2015  13,15
02/06/2015  13,15
03/06/2015  13,15
05/06/2015  13,65
08/06/2015  13,65
09/06/2015  13,65
10/06/2015  13,65
```
Quero apenas a taxa ontem:
```
$ zzselic ontem
Data        Taxa (%a.a.)
09/06/2015  13,65
```
Mais informações além da data e taxa:
```
$ zzselic -e ontem hoje
Data        Taxa (%a.a.)  Fator diário  Base de cálculo (R$)  Média  Mediana  Moda   Desvio padrão  Índice de curtose
09/06/2015  13,65         1,00050788    329.727.246.849,23    13,65  13,64    13,65  0,02           583,99
10/06/2015  13,65         1,00050788    326.866.340.280,20    13,65  13,64    13,65  0,02           1.318,21
```
Saída em CSV:
```
$ zzselic -c ontem …
```
=> Função nova zzselic: Consulta a taxa SELIC no site do Banco Central

testador/run
O clitest usa `/bin/sh` por padrão, o que em alguns sistemas aponta para outras shells que não o Bash. Isso afeta o funcionamento de algumas funções, que funcionam somente no Bash. Veja mais informações em https://github.com/funcoeszz/funcoeszz/issues/207
Este commit força que o testador seja sempre excutado usando o Bash.
=> Testador sempre usar Bash

testador/run
> https://github.com/funcoeszz/funcoeszz/pull/234#issuecomment-200294407
> O novo clitest usa um outro separador para o retorno das respostas inline, trocando "#→ " por "#=> ". É o caso também de fazer a troca nos testes, ou a clitest suportará ambos separadores?
Por ora, vamos somente dizer ao clitest para usar o marcador antigo, pra não precisar atualizar todos os nossos testes. Podemos fazer isso num passo posterior.
=> Forçar o testador a usar o prefixo inline #→

testador/zzmacvendor.sh, zz/zzmacvendor.sh
O antigo site apresentava uma instabilidade constante, não retornando resultado ou com tempo de resposta muito longo.
Testes durante uma semana mostraram que não era um fato corriqueiro, e deixando os testes no Travis muito demorado, que causava transtorno a outros testes não relacionados.
Nem mesmo a redução dos testes do ``` zzmacvendor ``` minimizou o problema, então o rumo tomado foi a troca de site a ser consultado.
Nessa nova "url" usada manteve a coerência dos resultados com o site antigo.
Veur issue #297
=> zzmacvendor: Alterando url de consulta, filtros e testador.

testador/zzcut.sh, testador/zzhsort.sh, testador/zztranspor.sh, zz/zzcut.sh, zz/zzhsort.sh, zz/zztranspor.sh
As funções ``` zzcut ```, ``` zzhsort ``` e ``` zztranspor ``` tem opções de delimitador de saída declarado de forma pouco usual como ``` --od ``` e ``` --ofs ```, e também de entrada ``` --fs ```.
Fato comentado pelo @aureliojargas em https://github.com/funcoeszz/funcoeszz/commit/ec80447488b32b2e6e623b614aaf0f8dc357722f#commitcomment-17344911
Então elimina-se a opção de delimitador entrada ``` --fs ``` e muda-se as opções de  delimitador de saída de  ``` --od ``` e ``` --ofs ``` para  ``` -D ``` e ``` --output-demilimiter ```.
=> Corrigindo declaração do delimitador de saída.

testador/zztestar.sh, zz/zztestar.sh
Alteração feita conforme descrito em:
- http://www.cisco.com/c/en/us/td/docs/net_mgmt/cisco_secure_access_control_server_for_windows/4-2/configuration/guide/acs42_config_guide/noagent.html#wp1017547
- https://en.wikipedia.org/wiki/MAC_address#Notational_conventions
=> zztestar: Suporte ao formato "0000.0000.0000" no Mac Address.

testador/zzfatorar.sh, zz/zzfatorar.sh
O site original mudou o foco e não há mais assunto relacionado a matemática.
Para que a função não perca a funcionalidade no Mac, o uso de um arquivo externo para formar o cache foi trocado pelo uso da função ``` zzdivisores ```.
=> zzfatorar: Deixando de usar cache externo.

funcoeszz
Na função ``` zztool list ``` embutido no core o ponto onde a variável está definida impedia o seu uso correto quando o browser usado é o ``` lynx ```.
=> Core: Redefinindo ponto de declaração da variável nbsp_utf.

zz/zzdicasl.sh, zz/zztradutor.sh
A troca de ``` zztool texto_em_iso ``` por ``` zzutf8 ``` visa deixar que a função analise a entrada e a converta conforme a necessidade, e não um passo obrigatório sempre.
Algumas distros conforme o locale tem uma saída de ``` encoding ``` comprometida com a forma anterior, e o uso da ``` zzutf8 ``` deixa-a mais portável.
=> zzdicasl e zztradutor: Trocando zztool 'texto_em_iso' por 'zzutf8'.

zz/zzfrenteverso2pdf.sh
Atualizando a função zzfrenteverso2pdf e inserindo um teste para verificar se o programa "pdftk", que é um pré requisito, está instalado.
=> Testa se "pdftk" existe em zzfrenteverso2pdf

util/alinhamento.sh
retirando função inexistente de exceção, e garantindo funcionamento caso a 'funcoeszz' não esteja no PATH.
=> Util: Alterando alinhamento.sh

testador/zzcinepolis.sh
A ideia dos testes é testar funcionalidades, para termos certeza que tudo está ok.
Não vejo razão para testar individualmente cada cinema, sendo que se funcionou para um, funcionará para os demais, visto que a fonte e o filtro é o mesmo para todos. Todas as dezenas de consultas ao site, uma para cada cinema, também estavam demorando para executar.
Por outro lado, não estavam sendo testadas as funcionalidades de detectar cidades inválidas e a de listar todas as cidades.
=> zzcinepolis: Adiciona testes de funcionaliade, remove repetidos

zz/zzlinuxnews.sh
A antiga redireciona para a nova, então vamos evitar o redirecionamento.
=> zzlinuxnews: Nova URL para Linux Today

util/nanny.sh
Antes essa exceção estava ativa somente na pasta `zz`.
=> Nanny: Ignora linha de requisitos na pasta off

funcoeszz, testador/zzzz.sh
Pra ajudar a debugar problemas do usuário e do contêiner.
Veja o diff ignorando os espaços em branco (`diff -w`),
na verdade só foi adicionada uma única linha.
=> zzzz: Agora mostra o browser padrão (lynx, links, etc)

zz/zzxml.sh
Senão dá erro no BSD.
Acabei de adicionar uma observação sobre isso lá na wiki:
https://github.com/funcoeszz/funcoeszz/wiki/Portabilidade
=> Portabilidade: comando t do sed tem que ser sozinho na linha

testador/zzlblank.sh, testador/zzxml.out.indent.xml, testador/zzxml.sh
Isso torna mais robustos os testes da zzlblank, que usa este conteúdo para seus
próprios testes.
Como estava, qualquer falha de comportamento na zzxml também quebrava os testes
da zzlblank. Agora ambos rodam de maneira independente.
=> Isola resultado da zzxml --indent num arquivo

testador/run
É chato ter que primeiro entrar na pasta do testador para poder usá-lo.
Com esta alteração, você pode chamar direto `~/funcoeszz/testador/run`, por
exemplo.
Você ainda precisa entrar na pasta primeiro se quiser usar glob para informar
mais de um arquivo para o testador. Mas os casos de uso mais comuns, de
informar apenas um arquivo, ou não informar nada para rodar todos os testes,
funcionará normalmente.
=> Executar o testador a partir de qualquer pasta

Dockerfile
Para poder dar um Ctrl-C durante a execução do contêiner, para interromper
imediatamente a função.
Sem isso, sinais como o Ctrl-C são ignorados.
Fixes #374
=> Usa dumb-init para capturar sinais (Ctrl-C)

README.md
Infelizmente, a nossa realidade é que sempre algo está quebrado, seja por problemas temporários em todos os servers envolvidos, atualizações dos sites, das ferramentas... Enfim.
Esse bagde sempre quebrado passa uma má impressão, que o software como um todo está quebrado, quando na verdade somente poucas funções estão quebradas (às vezes temporariamente).
=> Remove o build status

zz/zzcinemais.sh
Veja #395, nos comentários há a explicação do porquê destas mudanças: https://github.com/funcoeszz/funcoeszz/issues/395#issuecomment-261372327.
=> Usa zzutf8 em vez de texto_em_iso

zz/zzfeed.sh
Era necessárias no passado, quando o lynx era usado para baixar
os feeds. Agora que usamos o curl não há mais problema.
Nenhuma função utiliza essas opções:
$ git grep 'zzfeed.*iso'
$ git grep 'zzfeed.*utf'
$
Veja detalhes em #395
=> zzfeed: Remove opções obsoletas --iso e --utf

zz/zzxml.sh
Um complemento do PR #370 e em resposta ao issue #386.
=> zzxml: Prevenindo linhas 'vazias' com um espaço 'especial'.

zz/zzcpf.sh
Inserção de argumento -estado com propósito de identificar os estados federativos do cpf com base no 9º digito do mesmo.
Correção de validação de cpf com todos os dígitos iguais (000.000.000-00,...999.999.999-99).
=> zzcpf.sh - Identifica estado e validação extra

zz/zzconjugar.sh
Existia a função ``` zzconjuga  ``` criada em 05/08/2003 e desativada em 22/12/2010, e em 09/05/2016 foi criada a ``` zzconjugar ``` com a mesma premissa, e por descuido não foi verificada sua existência prévia.
Para corrigir a falha, seu autor e colaborador estão novamente constando no cabeçalho, e com a data de criação retroativa, e suas versões foram somadas.
=> zzconjugar: Restaurando data e autores originais.

funcoeszz
O shellcheck achou que `$esc[...` era a referência a um item de um array. Adicionei as chaves pra deixar claro que `$esc` é uma variável normal.
=> shellcheck: Evita confusão com sintaxe de array

util/nanny.sh
A zztool fica no core, não em zz/zztool.sh, então essa exceção pra ela não faz sentido. Ademais, faltava um `.sh` como parâmetro pro basename, então nem iria funcionar mesmo :P
=> nanny: Remove código não utilizado

util/nanny.sh, zz/zzarrumanome.sh
Dependências circulares definitivamente não são bem-vindas :)
O commit original desta linha da zzarrumanome (3c9d2dce) era de 2011!
=> nanny: Funções que citam a si mesmas no campo Requisitos

.travis.yml, testador/README.md, testador/run
Como a maioria dos erros são de funções que fazem consulta na internet, adotamos como padrão os testes limitados as funções cuja tag esteja assinalada internet. Tornando assim os testes mais velozes para a sequência de correções necessárias de funçoes quebradas.
=> Testes: Incluindo a opção de testes para funções que acessam internet.

zz/zzrastreamento.sh
O zzrastreamento estava com falha, abri o arquivo para tentar entender e verifiquei que o link do correio mudou. Fiz a alteração e rodou certinho.
endereço antigo:
http://www2.correios.com.br/sistemas/rastreamento/resultado_semcontent.cfm?
endereço atualizado (19/10/2019)
https://www2.correios.com.br/sistemas/rastreamento/resultado.cfm
Até o momento funcionando.
=> zzrastreamento alteracao endereco www de busca do correio

zz/zzmaiores.sh
Isso devido à saída do comando find que coloca espaços no início de cada linha. O comando `tr -s " "` que está na função `zz maiores` transforma vários espaços em um só, mas isto significa que ainda haverá um espaço no início das linhas do comando `find`. Para resolver o problema, simplesmente adicionei um próprio comando das funcoeszz: `zzlblank`. Dessa forma, garante-se que não haverá espaços iniciais.
Para exemplificar o que estava acontecendo no meu ambiente, segue a saída do `find -ls`:
```
13911760      8 -rw-r--r--   1 user  user      8105 Jul  4 21:41 ./arquivo1
13913962    124 -rw-r--r--   1 user  user    125099 Jul  4 22:19 ./arquivo2
13914195     12 -rw-r--r--   1 user  user      8923 Jul  4 21:41 ./arquivo3
13913802     16 -rw-r--r--   1 user  user     14741 Jul  4 21:41 …
```
=> A função zzmaiores com opção -f não funcionava no meu ambiente

.travis.yml, testador/run
Já faz quase 4 anos que desativamos os testes no OS X (vide PR #357),
então não tem sentido deixar esse código morto aqui. Se no futuro
quisermos reativar, basta reverter este commit.
=> Travis: Remove código relacionado ao OS X

testador/README.md, testador/run
Com essa mudança, é possível rodar somente os testes que não requerem
acesso à internet. Exemplo:
./testador/run local
=> testador: nova opção 'local' para testes sem acesso à internet

testador/zzarrumacidade.sh, zz/zzarrumacidade.sh
Esta mudança faz com que o zzarrumacidade corrija "jose" para "José" e "lourenco" para "Lourenço".
=> Corrige 'José' e 'Lourenço'

zz/zzmacaddress.sh
O comando ifconfig está presente em distribuições mais antigas, sendo substituído pelo comando ip que é mais abrangente nos sistemas atuais. Para manter uma maior compatibilidade, ao invés de substituir o comando, apenas inclui o novo comando ip para que seja funcional em sistemas antigos e atuais.
=> zzmacaddress: Incluindo o comando ip para suprir a ausência do ifconfig.

testador/zzcotacao.sh, zz/zzcotacao.sh
Economia UOL foi desconsiderada devido a bloqueios por excesso de uso.
=> zzcotacao: Ajustando a consulta apenas para o site da Infomoney.

zz/zzloteria.sh
Na primeira vez que a ` zzloteria ` é invocada, independente dos argumentos, o comportamento inicial era como se a ` zzloteria ` fosse executada sem argumentos, e depois cumpria o que se esperava.
Isso está ligado a atualização do cache, que pelas mudanças recentes do site de consulta, apresentam um comportamento diferente do que apresentavam antes. Então a chamada com o argumento '--atualiza' fica unicamente para atualizar o cache, sem dar prossegimento a qualquer consulta mesmo que sejam especificados nos demais argumentos.
=> zzloteria: Isolando atualização de cache.

testador/zzf1.sh, zz/zzf1.sh
Ideia baseada na sugestão do @aureliojargas na issue #514
=> Função nova: zzf1 - Mostra a classificação de pilotos e construtores da F1.

testador/zzdolar.sh
Em alguns casos, vem os centavos com apenas um dígito.
Agora o filtro sed trata se houver 3, 2 ou 1 dígito após a vírgula.
=> zzdolar: Atualiza testes

testador/zzpais.sh
A página da Wikipedia, onde estes dados são consultados, sofreu
alterações.
=> zzpais: Ajuste no resultado do teste

testador/run
A função ` zzchavepgp ` sofre com intermitência devido a instabilidade do site consultado: ` http://pgp.mit.edu `.
Em função dessa condição, ao qual não temos controle, foi retirado dos testes.
=> Travis: retirando zzchavepgp dos testes.

zz/zzcidade.sh
Por uma tecnicidade de  natureza jurídica e legal Brasília fica de fora da listagem do site, por isso está sendo colocado a revelia para constar na listagem da função.
O motivo da não inclusão pelo site pode ser visto em: https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_do_Brasil#cite_note-1
=> zzcidade: Incluindo Brasília na lista de municípios.

README.md, funcoeszz
O termo "GPLv2" pode gerar dúvida se é apenas a versão 2 mesmo, ou
versão 2 e mais recentes. Agora não há margem para dúvida.
Essa informação também foi colocada no README, para maior visibilidade.
=> Licença: deixa claro que é GPL-2.0-only

funcoeszz
Todas as funções da pasta `zz` possuem a extensão `.sh`.
Este código nunca era utilizado.
=> Remove suporte a arquivos sem extensão .sh

util/nanny.sh, util/requisitos.sh
Não é válido uma função declarar ela mesma como requisito, mesmo que
ela faça chamadas recursivas a si mesma.
A ideia dos requisitos são dependências em outras funções, pois a
função atual já está disponível, não é relevante essa informação.
Havia esta mesma verificação na Nanny, ela foi removida. A ideia é que
este script é o especialista em requisitos, e sabe melhor como detectar
os problemas.
=> util/requisitos.sh: Detecta função fazendo autoreferência

funcoeszz
Por algum motivo, essa função não tinha suporte ao `-h` e `--help`
para mostrar o texto de ajuda.
Arrumado.
=> zztool: Agora funciona -h, --help

util/nanny.sh
A versão anterior não estava funcionando corretamente quando havia mais
de uma linha longa em um mesmo arquivo, pois o `printf` colocava o nome
do arquivo somente na primeira linha, neste caso.
A lista de exceções pontuais foi revisada para incluir somente os casos
que acontecem atualmente.
=> Nanny: Melhora na detecção de linhas muito longas

.travis.yml, testador/funcoeszz.md, testador/run
O novo arquivo `testador/funcoeszz.md` serve como documentação e como
suíte de testes para o script principal `funcoeszz`, pra ter certeza que
ele funciona como esperado.
Note que o `clitest` ignora os textos explicativos, tudo o que importa
para ele são as linhas de comando e seus resultados.
O execução dos testes deste arquivo foi adicionada ao CI.
=> Adiciona testes para o core: funcoeszz

testador/missing.sh
Não precisava daquela firula toda quando só queremos comparar arquivos
em duas pastas diferentes.
=> testador/missing.sh: Simplifica

testador/zzcinemais.sh, zz/zzcinemais.sh
Aparentemente a ` zzutf8 ` não consegue identificar o corretamente a codificação, mesmo usando a ` zzencoding ` para essa tarefa, o que resulta numa saída com caracteres "estranhos".
A substituta ` zztool texto_em_iso ` faz a mesma tarefa, sem uma verificação prévia da codificação original.
A solução funciona, mas não identifico a origem do problema.
=> zzcinemais: Trocando 'zzuft8' por 'zztool texto_em_iso' devido a falha de conversão do site.

funcoeszz, zz/zzcep.sh, zz/zzchavepgp.sh, zz/zzddd.sh, zz/zzdicantonimos.sh, zz/zzdicsinonimos.sh, zz/zztool.sh
É uma sugestão, pois o funcionamento da variável era para seu uso em um sed na formatação, integral ou parcial, de uma url.
Mas sua característica e forma de uso parecem mais apropriada estar na ` zztool `, como suporte as demais funções.
=> Core e zztool: Substituindo a variável "$ZZSEDURL" por `zztool sedurl`.

info/requisitos.sh
O tratamento especial para a `zztool` não é mais necessário agora que
ela não está mais no core e fica na pasta `zz/` como as demais funções.
Dica: Veja esse diff ignorando espaços em branco (`-w`):
https://github.com/funcoeszz/funcoeszz/pull/698/files?diff=split&w=1
=> Simplifica info/requisitos.sh

funcoeszz, info/autores.sh, info/desativadas.sh, info/linhas.sh, info/quantidade.sh, info/requisitos.sh, manpage/generate.sh, release/2iso.sh, release/make-release.sh, testador/missing.sh, util/alinhamento.sh, util/checkbashisms.sh, util/metadata.sh, util/missing-requires.sh, util/nanny.sh, util/requisitos.sh, util/seguranca.sh
Esse commit arruma os problemas que o shellcheck
detectou com (falta de) aspas.
https://github.com/koalaman/shellcheck/wiki/SC2046
Quote this to prevent word splitting
https://github.com/koalaman/shellcheck/wiki/SC2086
Double quote to prevent globbing and word splitting
=> shellcheck: Arruma falta de aspas (SC2046, SC2086)

.shellcheckrc
Com o arquivo RC conseguimos ignorar algumas verificações que não nos
importam.
Note que o suporte ao arquivo de configuração só foi incluído na versão
0.7.0 do shellcheck.
=> shellcheck: Adiciona arquivo RC

testador/zzmacaddress.sh, util/alinhamento.sh, util/nanny.sh, util/requisitos.sh
Usar egrep/fgrep é considerado coisa do passado 🦕 
POSIX e GNU grep concordam (vide links).
https://github.com/koalaman/shellcheck/wiki/SC2196
SC2196: egrep is non-standard and deprecated
https://github.com/koalaman/shellcheck/wiki/SC2197
SC2197: fgrep is non-standard and deprecated
=> shellcheck: Arruma uso de egrep/fgrep (SC2196, SC2197)

funcoeszz, testador/funcoeszz.md
Desfaz parte do commit 4141711b, que removeu um trecho necessário.
Embora não haja mais nenhuma função ZZ neste arquivo, esse código ainda
é necessário quando o usuário executa a versão oficial, gerada pela
opção `--tudo-em-um`. Nesta versão todas as funções estão dentro do core
e estas linhas restauradas são necessárias para poder extrair os textos
de ajuda.
Também foram adicionados testes para a versão tudo-em-um, para garantir
que esta regressão não aconteça mais no futuro.
=> Arruma ajuda quebrada na versão tudo-em-um

funcoeszz, info/requisitos.sh, manpage/generate.sh, util/alinhamento.sh, util/checkbashisms.sh, util/metadata.sh, util/missing-requires.sh, util/nanny.sh, util/requisitos.sh
https://github.com/koalaman/shellcheck/wiki/SC2162
read without -r will mangle backslashes
https://github.com/koalaman/shellcheck/wiki/SC2035
Use `./*glob*` or `-- *glob*` so names with dashes won't become options
https://github.com/koalaman/shellcheck/wiki/SC2164
Use cd ... || exit in case cd fails
https://github.com/koalaman/shellcheck/wiki/SC1007
Remove space after = if trying to assign a value
=> shellcheck: Arruma SC2162, SC2035, SC2164, SC1007

util/requisitos.sh
A mudança recente na PR #702 adicionou um comentário na zztool que
passou a ser considerado um problema pelo script de requisitos:
$ ./util/requisitos.sh
zztool.sh: # Requisitos: zzcores
$
Agora o comentário é ignorado.
=> util/requisitos.sh: Novo falso-positivo na zztool

.travis.yml, util/requisitos.sh
O script requisitos.sh foi modificado para sair com exit code 1 caso
qualquer problema de requisitos seja encontrado.
Agora com o exit code correto, ele pode ser adicionado no Travis CI
para que possamos perceber problemas de requisitos assim que eles são
criados.
Um exemplo que poderia ter sido evitado foi o caso da PR #708.
=> CI: Agora executa o util/requisitos.sh

testador/run
A variável de ambiente ZZOFF estava influenciando os testes, porque não
estávamos desligando-na explicitamente ao dar source no funcoeszz na
fase de pre-flight do testador. Agora isso está explícito.
Sem ZZOFF no ambiente, os testes da `zzzz` passavam:
$ unset ZZOFF
$ ./testador/run zzzz.sh
...........
OK: 11 of 11 tests passed
Mas quando o usuário definia a ZZOFF, isso afetava os testes:
$ export ZZOFF="zzxml"
$ ./testador/run zzzz.sh
...
--------------------------------------------------------------------
[FAILED #3, line 46] zzzz | grep '(' | tr -d 0-9 | sed 's/) .*/) .../'
@@ -8,3 +8,4 @@
(  zshrc) ...
(   site) ...
((  funções disponíveis ))
+((  funções desativadas ))
--------------------------------------------------------------------
........
FAIL: 1 of 11 tests failed
=> testador/run: Ignora ZZOFF do ambiente do usuário

testador/zzzz.sh
Caso a variável `$ZZOFF` esteja definida, a saída da `zzzz` sem
argumentos é modificada. No final aparece uma seção nova listando as
funções desativadas. Exemplo:
$ ZZOFF="zzdata zzcores" ./funcoeszz zzzz
...
(( 188 funções disponíveis ))
ajuda, aleatorio, alfabeto, alinhar, ansi2html, arrumacidade,
...
vds, vira, wc, wikipedia, xml, zz
(( 2 funções desativadas ))
cores, data
$
Agora os testes verificam se esta funcionalidade está ok.
Os testes acabaram ficando um pouco complexos, devido a ter que criar os
arquivos `.on` e `.off` em uma pasta alternativa, pra não sobrescrever
os oficiais.
=> testador: zzzz: Adiciona teste com ZZOFF

testador/funcoeszz.md
Toda vez que o core é chamado, ele computa a lista de todas as funções
disponíveis e a lista das funções possivelmente desligadas pelo usuário
via variável `ZZOFF`. É com base nessas listas que o core decide se deve
carregar ou não cada função, bem como gerar seu texto de ajuda.
São gerados dois arquivos:
- `$ZZTMP.on` - Lista de todas as funções ligadas
- `$ZZTMP.off` - Lista de todas as funções desligadas
> IMPORTANTE: Na versão tudo-em-um, estes arquivos são criados, porém
> estão sempre vazios. Isso acontece porque a variável `ZZDIR` é
> requisito para a obtenção da lista de funções disponíveis, e essa
> variável não existe na versão tudo-em-um.
Os testes novos chamam o core de maneiras diferentes, com e sem
`ZZOFF`, para assegurar-se de que estes arquivos estão sendo gerados
como …
=> testador: core: Adiciona testes para os arquivos .on e .off

testador/funcoeszz.md
Deixa claro, tanto no texto quanto nos testes, que a `ZZOFF` só é
levada em conta quando se executa o core.
=> testador: core: Testa ZZOFF usada quando chamando uma função

zz/zzconfere.sh
Oi Aurelio!
Este glitch que resolvi aqui ocorria no Mac OS toda vez que se dava um `source "$ZZPATH"` na versão atual do funcoeszz.
Veja:
```
~/Downloads/Pessoal/etudes/etudes_bash/funcoeszz/zz $ source "$ZZPATH"
-bash: /Users/teixeira/Downloads/Pessoal/etudes/etudes_bash/funcoeszz/zz/zzconfere.sh: line 93: syntax error near unexpected token `;;'
-bash: /Users/teixeira/Downloads/Pessoal/etudes/etudes_bash/funcoeszz/zz/zzconfere.sh: line 93: `	;;'
~/Downloads/Pessoal/etudes/etudes_bash/funcoeszz/zz $ git stash pop
On branch master
Your branch is up to date with 'origin/master'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   zzconfere.sh
no changes added to commit …
```
=> Resolvendo glitch Mac OS Catalina e case/esac dentro de subshell.

.travis.yml, util/nanny.sh
Refactor e melhoria no funcionamento da Nanny, pra ela poder ser usada
no CI.
- Agora ela sai com exit code 1 quando algum check falha.
- A execução da Nanny foi adicionada ao Travis CI.
- Antes todos os checks eram sempre mostrados no output, independente
se falhou ou não. Agora só aparece na saída os checks que falharam.
Se nenhum check falhar, não terá nenhuma saída.
Nenhum check foi adicionado ou removido.
=> Nanny: CI, usa exit code, só mostra checks que falharam

testador/zzcoin.sh, zz/zzcoin.sh
Eu consigo acessar a URL da documentação da API normalmente pelo
navegador, porém, via linha de comando está dando erro:
$ curl https://www.mercadobitcoin.com.br/api-doc/
error code: 1020
$
Essa página era usada para extrair a lista das moedas disponíveis.
Em vez disso, agora a lista está hardcoded na função. Não é o ideal,
mas funciona.
Outras alterações:
- Mensagem de erro clara quando se informa uma moeda desconhecida.
- Testes atualizados.
- A saída foi modificada para sempre mostrar o nome da moeda antes
da cotação.
- Removida a opção `--all`. São 55 moedas ao todo, e o código anterior
neste caso fazia 55 requisições ao site. Me parece demais. Em seu lugar,
agora a função aceita receber múltiplas moedas como argumento.
=> zzcoin: cache local, removido --all, aceita múltiplas moedas

.travis.yml, Makefile, testador/run
Para centralizar comandos comuns para os desenvolvedores executarem
localmente.
O arquivo de configuração do Travis CI também foi adaptado para usar
os comandos novos.
Note que no Makefile também foi automatizada a instalação do clitest.
=> Adiciona Makefile

Makefile, util/alinhamento.sh, zz/zztool.sh
Exatamente a mesma coisa que foi feita no commit 1b248459, para a
nanny.sh, foi feita agora para o alinhamento.sh.
Também contém já os fixes para o $2, igual foi feito no commit
fec73478.
Também apaga um espaço em branco inútil, que foi o único problema
detectado pelo alinhamento.sh na master.
=> util/alinhamento.sh: CI, usa exit code, só mostra checks que falharam

.github/workflows/lint.yml, .travis.yml
A ideia é migrar do Travis CI (que ultimamente anda fazendo movimentos
estranhos, em seu modelo de negócios) para o GitHub Actions.
Aqui está um começo light, apenas dos linters.
=> Usa GitHub Actions para os linters

.travis.yml, testador/run
Não tem sentido só mostrar uma mensagem de erro, sendo que o clitest é
requisito obrigatório para rodar os testes.
A partir de agora, toda vez que o `testador/run` for chamado, ele
baixa o clitest caso seja necessário.
=> testador: Baixa clitest se necessário

testador/run, util/lista.sh
Novo script `util/lista.sh` cuja única função é listar as funções
disponíveis na pasta `zz/`, mostrando uma por linha.
Conforme os argumentos que recebe, filtra a lista de funções para
mostrar somente aquelas que acessam à internet, ou somente as que não
precisam de internet, etc.
O `testador/run` foi refatorado para usar este script novo, e também
ganhou uma pequena faxina para remover código duplicado.
=> Novo util/lista.sh, refactor do testador/run

testador/run, util/lista.sh
Removida a repetição dos nomes especiais de grupos de funções, que são
definidos em `util/lista.sh`, a agora não aparecem mais aqui.
Caso o argumento informado não seja reconhecido pelo script `lista.sh`,
então consideramos que os argumentos são nomes de arquivos de testes.
Outros:
- `util/lista.sh`: Agora as mensagens de erro são mandadas para o STDERR.
(como deveria ser desde o começo...)
=> testador/run: refactor

.github/workflows/test.yml
O Travis CI também está configurado para testar as funções que usam
a internet. Por enquanto, o GitHub Actions irá rodar em paralelo, pra
podermos comparar ambos.
A ideia é usar somente um no futuro, o que for melhor.
=> Usa GitHub Actions para testar as funções de internet

util/alinhamento.sh, zz/zzloteria.sh
Feita uma restruturação geral no código, para torná-lo mais fácil de
entender e dar manutenção.
A principal mudança é o uso de subfunções para isolar funcionalidades.
Assim podemos reutilizar e melhor organizar o código.
Note que as subfunções acabam "vazando" para o escopo global, então
todas elas devem ser apagadas (`unset`) em todas as condições de saída
da `zzloteria`, para que não vazem para a shell do usuário (veja a
função `zzloteria_faxina`).
Uma vantagem do uso de subfunções é remover código duplicado. Por
exemplo, todo o tratamento de download e atualização do cache de
resultados históricos das loterias agora está centralizado em
`zzloteria_atualiza_cache_historico()`.
Como as operações isoladas em subfunções, também ficou mais claro qual o
fluxo principal de operação da …
=> zzloteria: Refactor geral, usando subfunções

.github/workflows/test.yml
Atualizando o Ubuntu para a versão mais recente é possível usar a opção nova `--default-signal` do comando `env`. Com essa opção pode-se desfazer o `trap` do sinal SIGPIPE, que o GitHub Actions faz por padrão e afeta o funcionamento da suíte de testes.
Veja mais detalhes em:
https://github.com/aureliojargas/github-actions-sandbox/pull/4
=> CI: Usa Ubuntu 22.04 pra arrumar o SIGPIPE

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Estamos em 2022, e hoje há soluções muito bacanas para que se possa programar em um projeto, sem precisar bagunçar o seu ambiente local ([VS Code + devcontainer](https://code.visualstudio.com/docs/remote/containers)) ou até mesmo nem usar o ambiente local e fazer tudo pelo navegador ([GitHub Codespaces](https://github.com/features/codespaces)).
Para poder usar estas soluções, é preciso de uma imagem Docker que traga já instaladas todas as ferramentas que o programador precisa, além de uma configuração no arquivo `devcontainer.json`.
É isto o que este commit traz.
A imagem base (vide https://github.com/aureliojargas/devcontainer) é um Ubuntu 22.04 com git mais ferramentas de desenvolvimento para shell e Python.
Para as Funções ZZ, foi necessário instalar software adicional (`bc`, `gawk`, …
=> Imagem Docker para dev das ZZ (devcontainer, GitHub Codespaces)

.shellcheckrc, Makefile, funcoeszz, testador/run, util/lista.sh, util/nanny.sh
Agora é oficial, passaremos a exigir que os scripts não contenham problemas apontados pelo [shellcheck](https://www.shellcheck.net/), para poderem ser mergeados.
Por enquanto ainda não podemos ativar a verificação em todo o repositório, pois ainda há muito a arrumar. A partir desta PR, estamos verificando os seguintes locais:
- `funcoeszz` (core)
- `info/*.sh`
- `manpage/*.sh`
- `release/*.sh`
- `testador/run`
- `util/*.sh`
Veja os commits desta PR para mais informações.
Fica faltando a pasta `zz` com seus quase 200 arquivos shell lá dentro...
Issue: #691
=> Ativa shellcheck no Makefile e no CI
